name: scp test
on: push
jobs:
  scp-test:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/scp-action@v1
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          source: README.md
          target: ~
            


